create type "public"."event type" as enum ('check_in', 'check_out');

create table "public"."kunjungan" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null default auth.uid(),
    "check_in" timestamp with time zone not null default now(),
    "event" "event type" not null default 'check_in'::"event type"
);


alter table "public"."kunjungan" enable row level security;

CREATE UNIQUE INDEX kunjungan_pkey ON public.kunjungan USING btree (id);

alter table "public"."kunjungan" add constraint "kunjungan_pkey" PRIMARY KEY using index "kunjungan_pkey";

alter table "public"."kunjungan" add constraint "kunjungan_user_id_fkey" FOREIGN KEY (user_id) REFERENCES pengguna(user_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."kunjungan" validate constraint "kunjungan_user_id_fkey";

grant delete on table "public"."kunjungan" to "anon";

grant insert on table "public"."kunjungan" to "anon";

grant references on table "public"."kunjungan" to "anon";

grant select on table "public"."kunjungan" to "anon";

grant trigger on table "public"."kunjungan" to "anon";

grant truncate on table "public"."kunjungan" to "anon";

grant update on table "public"."kunjungan" to "anon";

grant delete on table "public"."kunjungan" to "authenticated";

grant insert on table "public"."kunjungan" to "authenticated";

grant references on table "public"."kunjungan" to "authenticated";

grant select on table "public"."kunjungan" to "authenticated";

grant trigger on table "public"."kunjungan" to "authenticated";

grant truncate on table "public"."kunjungan" to "authenticated";

grant update on table "public"."kunjungan" to "authenticated";

grant delete on table "public"."kunjungan" to "service_role";

grant insert on table "public"."kunjungan" to "service_role";

grant references on table "public"."kunjungan" to "service_role";

grant select on table "public"."kunjungan" to "service_role";

grant trigger on table "public"."kunjungan" to "service_role";

grant truncate on table "public"."kunjungan" to "service_role";

grant update on table "public"."kunjungan" to "service_role";

create policy "everyone can see kunjungan"
on "public"."kunjungan"
as permissive
for select
to public
using (true);


create policy "only logged in users can check in/check out"
on "public"."kunjungan"
as permissive
for insert
to authenticated
with check (true);



